config/routes.rb
Rails.application.routes.draw do
devise_for :users, :controllers => { :omniauth_callbacks => 'callbacks', registrations: 'registrations' }
  
  root to: "application#home"
  resources :invoices
  resources :clients
  resources :projects
  resources :users


  resources :projects do
    resources :clients
  end

  resources :clients do
    resources :projects
  end
  resources :invoices do 
    resources :users
  end
  resources :projects do 
    resources :invoices
  end
  
end

app/models/user.rb
class User < ApplicationRecord

	has_many :clients
	has_many :invoices
	has_many :projects, through: :invoices
  has_many :projects, through: :clients

  validates :name, presence: true
	validates :email, presence: true
	validates :email, uniqueness: true
  
	devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable, :omniauthable, :omniauth_providers => [:facebook, :google_oauth2]

  def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.name = auth.info.name
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,10]
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    if params[:id]
    @user = User.find(params[:id])
  end
  end

end  

app/views/users/show.html.erb
<div class="col-md-12">
<h1>Your Profile Information: </h1>
<hr>

<table class="table table-hover">
			<thead  class="table-active">	
				<tbody class="table-default" >
					<tr>
					<td> Name: </td>
					<td><%=current_user.name %> </td>
					</tr>
					<tr>
					<td> Email: </td>
					<td><%=current_user.email %> 
					</td>
					</tr>
					<tr>
					<td> Business Name: </td>
					<td><%=current_user.business_name %> </td>
					</tr>
					<tr>
					<td> Business Address: </td>
					<td><%=current_user.business_address %> </td>
					</tr>
					<tr>
					<td> Business ID (EIN or alike): </td>
					<td><%=current_user.business_id %> </td>
					</tr>
				</tbody>
			</thead>
</table>
<br>
<h4> <%= link_to "Update", edit_user_registration_path(current_user), :class => "btn btn-success btn-md"%>
<%= link_to "Delete Your Account", registration_path(current_user), method: :delete,  data: { confirm: "Are you sure you want to delete your account?" }, :class => "btn btn-danger btn-md"  %></h4>
</div>

				
		