config/routes.rb
Rails.application.routes.draw do
devise_for :users, :controllers => { :omniauth_callbacks => 'callbacks', registrations: 'registrations' }
  
  root to: "application#home"
  resources :invoices
  resources :clients
  resources :projects
  resources :users


  resources :projects do
    resources :clients
  end

  resources :clients do
    resources :projects
  end
  resources :invoices do 
    resources :users
  end
  resources :projects do 
    resources :invoices
  end
  
end

app/models/client.rb
class Client < ApplicationRecord
	belongs_to :user
	has_many :projects
	has_many :invoices, through: :projects
	validates_presence_of :business_name
	validates :business_name, :uniqueness => {:scope=>:user_id}
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
	before_action :current_user
	
	def index
 			@clients = current_user.clients.order! 'created_at DESC'
 			respond_to do |format|
 			format.html {render :index}
 			format.json {render json: @clients}
 		end
 	end

	def new
		@client = Client.new
	end


	def show
		set_client
		respond_to do |format|
			format.html {render:show}
			format.json {render json: @client}
		end
	end

	
	def edit
		set_client
	end

	def create
		@client = current_user.clients.build(client_params)
		if @client.save
			# render json: @client
			# respond_to do |format|
			# format.html {render:show}
			# format.json {render json: @client}
			render :show
			# end
		else
			redirect_to new_client_path
		end
	end

	 def update 
	 	set_client
    	if @client.update(client_params)
      	   redirect_to clients_path
        else 
          set_client
          render :edit
         end
  	end

	 def destroy
	 	set_client
	 	@client.destroy
	 	redirect_to clients_path
  	end

	private

	def client_params
		params.fetch(:client, {}).permit(:business_name, :address, :email, :website, project_ids: [])
	end


	def set_client
		@client = Client.find_by(id: params[:id])
		if !@client
			redirect_to clients_path
		end
	end


end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
	<div class="col-md-6">
		<%= form_for(@client) do |c| %>
			<%= render partial: 'layouts/errors', locals: {object: @client} if @client.errors.count != 0 %>
			<div class="form-group">	
				<label> Client Name: </label><br>
				<%=  c.text_field :business_name,  :placeholder=>"Required", :class => "form-control" %><br>
			</div>	
			<div class="form-group">
				<label> Address: </label><br>
				<%=  c.text_field :address, :placeholder=>"Enter address", :class => "form-control"  %><br>
			</div>
			<div class="form-group">
				<label> Website: </label><br>
				<%=  c.text_field :website, :placeholder=>"Enter website", :class => "form-control" %><br>
			</div>
			<div class="form-group">
				<label> Email: </label><br>
				<%=  c.email_field :email, :placeholder=>"Enter email", :class => "form-control"  %><br>
			</div>
			      <br>
				<%= c.submit :class => "btn btn-primary" %>
		<%end%>
	</div>

app/views/clients/_links.html.erb
<%= link_to "Cancel", clients_path %><br>
<%= link_to "Delete", @client, method: :delete, data: { confirm: "Are you sure you want to delete this client?" } %>

app/views/clients/edit.html.erb
<h2>Edit your existing client record: </h2>
	<%= render 'form' %>
<br>
  	<%= render 'links' %>
</p>

app/views/clients/index.html.erb
	<div class="row">
		<div class="col-sm-6">
				<div class="container">	
				<% if @clients.count != 0 %>
					<br>
					<h3>Your Clients:</h3>
					<form class="form-inline my-2 my-lg-0">	
						<input class="form-control mr-sm-2" id="search" type="text" placeholder="Search" aria-label="Search">
					</form><br/>
					</div>
						<div class="index" align="left" style="overflow: auto;">
							<ol id="xyz">
							<% @clients.each do |c| %>
								<h5><li id="name"><%=c.business_name%></li>
								<form action="<%=client_path(c)%>" method="get" style="display:inline-block">
									<button type="submit" class="btn btn-primary btn-md" value="Clients" style="display:inline-block">Client View Page</button>
									<button class="js-more btn btn-success btn-md" data-id="<%= c.id %>">Quick Info</button></h5>
								</form>	
							<% end %>	
							</ol>			
						</div>	
					</div>

		<div class="col-sm-6">
			<br>
			<h4>To add full details of a new client click<br> 
			<%=link_to "HERE", new_client_path, :class => "btn btn-primary btn-md"%> or 
			<button class="js-new btn btn-success btn-md">Quick Add</button> </h4>
		<%else %>
			<h3 style="color:red">You currently have no clients. To add a new client click <%=link_to "HERE", new_client_path%>.</h3>
		<%end%>
			<h3><div id="new-client"></div></h3>
			<h3><div id="client-show" align="left"></div></h3>
		</div>
	</div>
</div>

app/views/clients/new.html.erb
<%= render partial: 'layouts/errors', locals: {object: @client} if @client.errors.count != 0 %>

<h2>Create a new client record: </h2>
<br>
<%= render 'form' %>

app/views/clients/show.html.erb
	<div class="container">
		<br>	
			<h2><%=@client.business_name%></h2>
		<br>
			<div class="row">
				<div class="col-md-6">
					<div class="mapouter"><div class="gmap_canvas"><iframe width="100%" height="300" id="gmap_canvas" src="https://maps.google.com/maps?q=<%=@client.address%>&t=&z=13&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe></div><style>.mapouter{position:relative;text-align:right;height:auto;max-width:100%;}.gmap_canvas {overflow:hidden;background:none!important;height:auto;max-width:100%;}</style>
					</div>
				</div>
			<div class="col-md-6">
				<h4>Address: <%=@client.address%></h4>
				<h4>Email: <a href = "mailto: <%=@client.email%>"><%=@client.email%></a></h4>
				<h4>Website: <a href="<%=@client.website%>"><%=@client.website%></a></h4>

					<div style="display: inline"><h4>Projects: <button class="btn btn-primary btn-md projects_view"  data-id="<%= @client.id %>">Quick View</button>&nbsp<%= link_to "Go to Projects", client_projects_path(@client), :class => "btn btn-primary btn-md"%>&nbsp<%= link_to "Add New", new_client_project_path(@client), :class => "btn btn-primary btn-md"%></h4></div>

				<table class="table table-bordered table-hover">
					<thead  class="table-active" id="table show" style="display: none;">
						<tr>
							<th>No.</th>
							<th>Project</th>
							<th></th>
						</tr>
					</thead>
						<tbody class="table-default" id="projects_show"></tbody>
				</table>

					<div style="display: inline"><h4> <%= link_to "Edit Client Information", edit_client_path(@client), :class => "btn btn-success btn-md"%>
						<%= link_to "Delete Client Record", @client, method: :delete,  data: { confirm: "Are you sure you want to delete this client?" }, :class => "btn btn-danger btn-md"%></h4></div>
			</div>
		</div>
	</div>