config/routes.rb
Rails.application.routes.draw do
devise_for :users, :controllers => { :omniauth_callbacks => 'callbacks', registrations: 'registrations' }
  
  root to: "application#home"
  resources :invoices
  resources :clients
  resources :projects
  resources :users


  resources :projects do
    resources :clients
  end

  resources :clients do
    resources :projects
  end
  resources :invoices do 
    resources :users
  end
  resources :projects do 
    resources :invoices
  end
  
end

app/models/project.rb
class Project < ApplicationRecord
	belongs_to :client
	has_many :invoices
	has_many :users, :through => :invoices
	validates :description, presence: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :current_user

	def new
		# check if nested and its a proper id
		if params[:client_id] && @client = Client.find_by_id(params[:client_id].to_i)
		@project = Project.new(client_id: params[:client_id].to_i)
		else
		#unnested
		@project = Project.new
	end
	end

	
	def index
		if params[:client_id]
			@client = Client.find_by_id(params[:client_id].to_i)
			@projects = @client.projects.order! 'created_at DESC'
		else
		@projects = current_user.projects.order! 'created_at DESC'
		respond_to do |format|
 			format.html {render :index}
 			format.json {render json: @projects}
 		end
	end
	end

	def edit
		set_project
	end

	def show
		@project = Project.find(params[:id].to_i)
		@client = Client.find(@project.client_id)
		respond_to do |format|
			format.html {render:show}
			format.json {render json: @project}
		end
	end

	def update 
	 	set_project
    	if @project.update(project_params)
      	redirect_to projects_path
     else 
      set_project
      render :edit
    end
  end

	def create
		@project = current_user.projects.build(project_params)
		if @project.save
			redirect_to project_path(@project)
		else
			render :new
		end
	end

	def destroy
	 	set_project
	 	@project.destroy
	 	redirect_to projects_path
  	end

	private

	def project_params
		params.require(:project).permit(:description, :client_id, invoice_ids: [])
	end

	def set_project
		@project = Project.find_by(id: params[:id].to_i)
	end
end

app/helpers/projects_helper.rb
module ProjectsHelper
	def sort(projects)
	    projects.order! 'created_at DESC'
	end

	def created_date(project)
		project.created_at.strftime("%b %e, %Y")
	end

end

app/views/projects/_form.html.erb
<%= form_for(@project) do |p| %>
<%= render partial: 'layouts/errors', locals: {object: @project} if @project.errors.count != 0 %>
	<label> Project description: </label><br>
	<%= p.hidden_field :client_id %><br>
	<%=  p.text_area :description %><br>
	<%= p.submit %>
<%end%>

app/views/projects/_index.html.erb
<br>
<table class="table table-bordered table-hover">
	<thead  class="table-active">
		<tr>
			<th>Project</th>
			<th>Client</th>
			<th>Created</th>
			<th></th>
		</tr>
	</thead>
	<tbody class="table-default">
		<% @projects.each do |p| %>
		<tr>
			<th><%= p.description %></th>
			<td><%= p.client.business_name %></td>
			<td><%= created_date p %></td>
			<td class="text-center"><%= link_to "Open", project_path(p), :class => "btn btn-primary btn-md" %>&nbsp<%= link_to "Edit", edit_project_path(p), :class => "btn btn-success btn-md" %>&nbsp<%= link_to "Delete", p, method: :delete,  data: { confirm: "Are you sure you want to delete this project?" }, :class => "btn btn-danger btn-md"%></td>
		</tr>
		<%end%>
	</tbody>
</table>

app/views/projects/edit.html.erb
<h4> Edit your project information: </h4>
<%= render 'form' %>

app/views/projects/index.html.erb
<% if params[:client_id] %>
<br>
<h2> Your projects for <%=@client.business_name%>: </h2>
	<%=render 'index' %>
<%elsif @projects.count !=0 %>
<br>
	<%=render 'index' %>
<%else%>
<h2 style="color:red"> You currently have no projects. To create a new project, you need to add it to an existing client. See your client list <%= link_to "HERE", clients_path %></h2>
<%end%>

app/views/projects/new.html.erb
<h4> Enter your new project: </h4>
<%= render 'form' %>

app/views/projects/show.html.erb
<div class="container">
	<div class="col-md-12">
	<br>
		<h4 align="center">Project name: <%=@project.description%> <br/> Client: <%=@project.client.business_name %></h4><br />
</div>
<br/>
	<%if @project.invoices %>
		<h3>Issued invoices</h3>
		
		<table class="table table-hover">
			<thead  class="table-active">		
				<tr>
					<th>No.</th>
					<th>Date</th>
					<th>Service</th>
					<th>Rate</th>
					<th>Quantity</th>
					<th>Total</th>
					<th></th>
					</tr>		
			<tbody class="table-default" >
				<% @project.invoices.each_with_index do |i, index| %>
					<td><%= index + 1 %></td>
					<td><%= created_date i %></td>
					<td><%= i.service %></td>
					<td><%= i.rate %></td>
					<td><%= i.amount %></td>
					<td>$<%= i.total %></td>
					<td><%=link_to "Open", invoice_path(i), :class => "btn btn-primary btn-md"%> &nbsp<%= link_to "Edit", edit_invoice_path(i), :class => "btn btn-success btn-md" %>&nbsp<%= link_to "Delete", i, method: :delete,  data: { confirm: "Are you sure you want to delete this invoice?" }, :class => "btn btn-danger btn-md"%></td>
				</tbody>
				<% end %>
			</thead>
		</table>
	<% else %>
		<h4> This project has no invoices </h4>
	<% end %>

	<form action="<%=edit_project_path(@project)%>" method="get" style="display:inline-block">
	<button type="submit" class="btn btn-primary btn-md" value="edit_projects">Edit Project Info</button></form>
	<form action="<%=new_project_invoice_path(@project)%>" method="get" style="display:inline-block">
	<button type="submit" class="btn btn-primary btn-md" value="create_invoice">New Invoice for This Project</button>
	</form>
	<div style="display:inline-block"><%= link_to "Delete Project", @project, method: :delete, data: { confirm: "Are you sure you want to delete this project?" }, :class => "btn btn-danger btn-md"%></div>
	</div>
</div>