config/routes.rb
Rails.application.routes.draw do
devise_for :users, :controllers => { :omniauth_callbacks => 'callbacks', registrations: 'registrations' }
  
  root to: "application#home"
  resources :invoices
  resources :clients
  resources :projects
  resources :users


  resources :projects do
    resources :clients
  end

  resources :clients do
    resources :projects
  end
  resources :invoices do 
    resources :users
  end
  resources :projects do 
    resources :invoices
  end
  
end

app/views/layouts/_alerts.html.erb
		<br>
		<br>
		<br>


		<% if notice%>
			<div class="alert alert-success col-md-4 col-centered" role="alert"><h5><p class="notice" ><%= notice %></p></h5></div>
 		<% elsif alert && !current_user%>
			 <div class="alert alert-danger col-md-4 col-centered" role="alert"><h5><p class="alert" ><%= alert %></p></h5></div>
		<% end %>

app/views/layouts/_errors.html.erb
<ul> 
<% object.errors.full_messages.each do |msg| %>
<div class="alert alert-danger" role="alert"><h3 style="color: red"><li><%= msg %></li></h3></div>
<%end%>
</ul>

app/views/layouts/_nav.html.erb
<%if user_signed_in? %>
<nav class="navbar navbar-expand-md navbar-light bg-light nav-pills flex-column font-weight-bold"  style="width: 100%; background-color:rgba(222, 225, 230)">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation" >
            <span class="navbar-toggler-icon"></span>
          </button>
        <div class="collapse navbar-collapse" id="navbarNav">

          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="<%=root_path%>">HOME</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="<%=clients_path%>">CLIENTS</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="<%=projects_path%>">PROJECTS</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="<%=invoices_path%>">INVOICES</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="<%=user_path(current_user)%>">PROFILE</a>
            </li>
            <li class="nav-item active">
			<%= link_to "LOGOUT", destroy_user_session_path, method: :delete, :class => 'nav-link'  %>
            </li>
          </ul>
        </div>
      </nav>
      <%else%>
      <nav class="navbar navbar-expand-lg navbar-light bg-light nav-pills flex-column font-weight-bold"  style="width: 1200px;">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="<%=new_user_registration_path %>">SIGN UP<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="<%=new_user_session_path%>">LOG IN</a>
            </li>
            </ul>
        </div>
      </nav>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html
style="width: 100%;
height: 100%">
  <head>
    <title>ClientTrackerRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet"
  href="https://fonts.googleapis.com/css?family=Montserrat">
    <style>
body {
  background: #e7f1f8;
  background-size:     cover;                      /* <------ */
  background-repeat:   no-repeat;
  background-position: center center;  
  color:  #0E1422;
  font-family: 'Montserrat', serif;
  /* text-shadow: 0.2px 0.5px #000000; */
}
 </style>

  </head>

  <body>
    <div class="container">
    <div class="nav"><%=render 'layouts/nav'%></div>
    <%=render 'layouts/alerts'%>
    <div id="thing">
    <%= yield %>
  </div>
  </div>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Invoice PDF</title>
  <%= wicked_pdf_stylesheet_link_tag "application" %>
</head>
<body>

  <%= yield %>

</body>
</html>